config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "brekkies#index"
  resources :brekkies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brek.rb
class Brek < ApplicationRecord
  validates :message, presence: true

  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :breks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brekkies_controller.rb
class BrekkiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    @brek = Brek.find_by_id(params[:id])
    return render_not_found if @brek.blank?
    return render_not_found(:forbidden) if @brek.user != current_user

    @brek.destroy
    redirect_to root_path
  end

  def update
    @brek = Brek.find_by_id(params[:id])
    return render_not_found if @brek.blank?
    return render_not_found(:forbidden) if @brek.user != current_user

    @brek.update_attributes(brek_params)
    if @brek.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def new
    @brek = Brek.new
  end

  def index
    @brek = Brek.all
  end

  def show
    @brek = Brek.find_by_id(params[:id])
    return render_not_found if @brek.blank?
  end

  def edit
    @brek = Brek.find_by_id(params[:id])
    return render_not_found if @brek.blank?
    return render_not_found(:forbidden) if @brek.user != current_user
  end

  def create
    @brek = current_user.breks.create(brek_params)
    if @brek.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def brek_params
    params.require(:brek).permit(:message, :picture)
  end

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brekkies_helper.rb
module BrekkiesHelper
end

app/views/brekkies/edit.html.erb
<%= simple_form_for @brek do |f| %>
  <%= f.input :message %>
  <%= f.submit %>
<% end %>

app/views/brekkies/index.html.erb
<h1>Brekkies</h1>

<% @brek.each do |brek| %>
<div>
  <%= brek.message %>
  <%= image_tag brek.picture %>
</div>
<% end %>

app/views/brekkies/new.html.erb
<h1>New Brekkie</h1>

<%= simple_form_for new_brekky_path(@brek) do |f| %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit "Post!" %>
<% end %>

app/views/brekkies/show.html.erb
<%= @brek.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brekkie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      You're signed in as <%= current_user.email %>.
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>